### PR TITLE
I made your code better

### PR DESCRIPTION
**Pull request by lolPants**
https://i.imgur.com/uyKgrYk.gif

### CODE REVIEW

**Comment by The-Jonsey** [comment]
so this isnt the first time you've tried pulling (haha) this shit.

**Comment by md678685** [comment]
I'm ~~not~~ sorry that I didn't use your exact personal JS style, and ~~not~~ particularly apologetic that I didn't use a `src/` root for source for a project that doesn't require a build step and therefore has no reason to use `src/` as a root. I will make sure to make my code better ~~by ignoring your so-called "improvements"~~ in the future.

This didn't improve anything and now has merge conflicts, so there's no reason for me to merge it. Feel free to resubmit a PR if you feel that you can "make my code better" with a clear description (read: not an arrogant gif) of what improvements your PR contains.

**Comment by lolPants** [comment]
¯\_(ツ)_/¯

**Pull request closed without merging**
